In [ ]:
!pip install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="Y10vh3ZwlwXaBpUEcDJ3")
project = rf.workspace("mahmoud-9wyf6").project("test2-fire-and-smoke")
version = project.version(2)
dataset = version.download("yolov8")


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.9/49.9 MB 17.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 47.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 86.1 MB/s eta 0:00:00
  Attempting uninstall: opencv-python-headless
    Found existing installation: opencv-python-headless 4.12.0.88
    Uninstalling opencv-python-headless-4.12.0.88:
      Successfully uninstalled opencv-python-headless-4.12.0.88
  Attempting uninstall: idna
    Found existing installation: idna 3.11
    Uninstalling idna-3.11:
      Successfully uninstalled idna-3.11
loading Roboflow workspace...
loading Roboflow project...



Extracting Dataset Version Zip to Test2-Fire-and-Smoke-2 in yolov9:: 100%|██████████| 5876/5876 [00:00<00:00, 11252.88it/s]


In [2]:
!pip install ultralytics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 36.9 MB/s eta 0:00:00


In [3]:
yaml_content="""names:
- Fire
- Smoke
nc: 2
roboflow:
  license: CC BY 4.0
  project: test2-fire-and-smoke
  url: https://universe.roboflow.com/mahmoud-9wyf6/test2-fire-and-smoke/dataset/2
  version: 2
  workspace: mahmoud-9wyf6
test: "/content/Test2-Fire-and-Smoke-2/test/images"
train: "/content/Test2-Fire-and-Smoke-2/train/images"
val: "/content/Test2-Fire-and-Smoke-2/valid/images"
"""
file_path = "/content/Test2-Fire-and-Smoke-2/data.yaml"

with open(file_path, "w") as file:
    file.write(yaml_content)

print(f"YAML file saved at {file_path}")


YAML file saved at /content/Test2-Fire-and-Smoke-2/data.yaml


In [ ]:
from ultralytics import YOLO
#  Load a pretrained model or create a new one.
#  If no model is specified, YOLOv8 will create a new one.
model = YOLO('yolov8s.pt')  # Load a pretrained model (e.g., yolov8s.pt, yolov8m.pt, etc.)
# Train the model
results = model.train(data='/content/Test2-Fire-and-Smoke-2/data.yaml', epochs=20)
results = model.val()

Creating new Ultralytics Settings v0.0.6 file ✅ 
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
PRO TIP 💡 Replace 'model=yolov5s.pt' with new 'model=yolov5su.pt'.
YOLOv5 'u' models are trained with https://github.com/ultralytics/ultralytics and feature improved performance vs standard YOLOv5 models trained with https://github.com/ultralytics/yolov5.

Ultralytics 8.3.235 🚀 Python-3.12.12 torch-2.9.0+cu126 CUDA:0 (Tesla T4, 15095MiB)
engine/trainer: agnostic_nms=False, amp=True, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/Test2-Fire-and-Smoke-2/data.yaml, degrees=0.0, deterministic=True, 

In [5]:
pip install gradio

In [6]:
from ultralytics import YOLO

# Load the best trained model
model = YOLO('/content/runs/detect/train/weights/best.pt')

# Specify the path to your input image
# For example, let's use an image from the validation set
input_image_path = '/content/Test2-Fire-and-Smoke-2/test/images/10-9-15-2-400_jpg.rf.54209eba99451cb9f4a3c6a1780e677c.jpg' # Replace with your image path

# Perform object detection on the image
results = model.predict(source=input_image_path, save=True, conf=0.25)

# Show results
for r in results:
    print(r.boxes.xyxy) # Bounding box coordinates
    print(r.boxes.conf) # Confidence scores
    print(r.boxes.cls)  # Class labels

print(f"Predictions saved to: {results[0].save_dir}")


image 1/1 /content/Test2-Fire-and-Smoke-2/test/images/10-9-15-2-400_jpg.rf.54209eba99451cb9f4a3c6a1780e677c.jpg: 640x640 4 Fires, 29.5ms
Speed: 8.0ms preprocess, 29.5ms inference, 9.6ms postprocess per image at shape (1, 3, 640, 640)
Results saved to /content/runs/detect/predict
tensor([[1.5392e+02, 4.9598e-01, 2.2203e+02, 1.7855e+02],
        [2.2762e+01, 3.8324e-02, 1.0802e+02, 1.1610e+02],
        [3.4551e+01, 1.7496e+02, 4.5129e+01, 2.0227e+02],
        [3.6383e+01, 1.8008e+02, 4.3022e+01, 2.0164e+02]], device='cuda:0')
tensor([0.4373, 0.3722, 0.3672, 0.2941], device='cuda:0')
tensor([0., 0., 0., 0.], device='cuda:0')
Predictions saved to: /content/runs/detect/predict


In [9]:
import gradio as gr
from ultralytics import YOLO
import cv2
import numpy as np
from PIL import Image

model = YOLO('/content/runs/detect/train/weights/best.pt')

def predict_image(img):
    img_np = np.array(img)
    results = model.predict(source=img_np, save=False, conf=0.25)

    for r in results:
        im_array = r.plot()
        output_img = Image.fromarray(im_array[..., ::-1])

    return output_img

iface = gr.Interface(
    fn=predict_image,
    inputs=gr.Image(type="pil", label="Upload Image"),
    outputs=gr.Image(type="pil", label="Detected Objects"),
    title="YOLO Detection",
    description="Upload an image for detection.",
    live=False
)

# FIX event-loop bug
iface.queue(False)

iface.launch(debug=False)


It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://948538549236a8c923.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
